### PR TITLE
fix: use rocky_version variable to template rocky_iso_download_url

### PR DESCRIPTION
**Pull request by hbjydev**

### CODE REVIEW

**Comment by tcooper** [comment]
@hbjydev We might want a tweak to what you've provided here. I believe it's preferable to use only the MAJOR version in that part of the URL and I've seen cases where using MAJOR.MINOR can cause issues. @NeilHanlon can you comment/confirm/review?

**Comment by NeilHanlon** [comment]
Correct. would be good to make sure we're using the major version only here.

**Comment by hbjydev** [comment]
My issue with that is that you guys are also inserting the checksums. Surely that means that on a new image being released, the playbook(s) using this file would just stop working?

if that’s not a concern or anything then fair enough, I can tweak.

**Comment by tcooper** [comment]
It's true, for each new release we must update the data used by the playbook. Unless we implement a pull of the CHECKSUM file, verify the GPG sig and then use the contents this is what is required. We've had issues with bad (cached) ISOs at various times the CHECKSUM validation prevents those from creeping in.

**Pull request closed without merging**
